version: "3.4"
services:
  php:
    build:
      context: docker/php
      target: ${ENVIRONMENT:-production}
    volumes:
      - .:/app:delegated

  nginx:
    build:
      context: docker/nginx
      target: ${ENVIRONMENT:-production}
    ports:
      - ${PORT_HTTP:-8080}:80
    volumes:
      - .:/app:delegated
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

