version: "3.4"
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: ${ENVIRONMENT:-production}
    volumes:
      - .:/project:delegated

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      target: ${ENVIRONMENT:-production}
    ports:
      - ${PORT_HTTP:-8080}:80
    volumes:
      - .:/project:delegated
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
      target: ${ENVIRONMENT:-production}
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: k3
      MYSQL_USER: k3user
      MYSQL_PASSWORD: pass
      TZ: Asia/Tokyo
    volumes:
      - .:/project:delegated
      - ./docker/mysql/conf.d/mylogin.cnf:/etc/mysql/conf.d/mylogin.cnf
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    security_opt:
      - seccomp:unconfined

volumes:
  mysql:

